config/routes.rb
Rails.application.routes.draw do
  resources :tic_tac_toe_boards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tic_tac_toe_board.rb
class TicTacToeBoard < ApplicationRecord
    has_many :tic_tac_toe_players
end

app/models/tic_tac_toe_player.rb
class TicTacToePlayer < ApplicationRecord
    belongs_to :tic_tac_toe_board
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tic_tac_toe_players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tic_tac_toe_boards_controller.rb
class TicTacToeBoardsController < ApplicationController
  before_action :set_tic_tac_toe_board, only: %i[ show edit update destroy get_table ]

  # GET /tic_tac_toe_boards or /tic_tac_toe_boards.json
  def index
    @tic_tac_toe_boards = TicTacToeBoard.all
  end

  # GET /tic_tac_toe_boards/1 or /tic_tac_toe_boards/1.json
  def show
    @player1 = @tic_tac_toe_board&.tic_tac_toe_players&.first&.user&.username
    @player2 = @tic_tac_toe_board&.tic_tac_toe_players&.last&.user&.username
    @turn_on_play = @tic_tac_toe_board&.tic_tac_toe_players.where("tic_tac_toe_players.is_active is true")&.first
    @initial = @turn_on_play&.initial
    @initial = @initial.present? ? @initial : 'X'
    @user_turn_on_play = @turn_on_play&.user&.username
    @the_winners = @tic_tac_toe_board&.tic_tac_toe_players&.where("tic_tac_toe_players.is_winners = ?", true)&.first&.user&.username || "-"
  end

  # GET /tic_tac_toe_boards/new
  def new
    @tic_tac_toe_board = TicTacToeBoard.new
  end

  # GET /tic_tac_toe_boards/1/edit
  def edit
  end

  # POST /tic_tac_toe_boards or /tic_tac_toe_boards.json
  def create
    tic_tac_toe_player = TicTacToePlayer.new
    ActiveRecord::Base.transaction do
      begin
        @tic_tac_toe_board = TicTacToeBoard.create
        params[:users].each_with_index do |user, index|
          player = index + 1
          @user = User.create(username: user[:username], player: player)
          if @user
            initial = player == 1 ? 'X' : 'O'
            tic_tac_toe_player = TicTacToePlayer.create(user_id: @user.id, tic_tac_toe_board_id: @tic_tac_toe_board.id, initial: initial)
          end
        end if @tic_tac_toe_board
        # tic_tac_toe_player.errors.add(:base, "Rollback")
        # raise ActiveRecord::Rollback
      rescue ActiveRecord::RecordNotFound => e
        tic_tac_toe_player.errors.add(:base, e)
        raise ActiveRecord::Rollback
      end
    end
    
    respond_to do |format|
      if tic_tac_toe_player.errors.present?
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tic_tac_toe_board.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to tic_tac_toe_board_url(@tic_tac_toe_board), notice: "Tic tac toe board was successfully created." }
        format.json { render :show, status: :created, location: @tic_tac_toe_board }
      end
    end
  end

  # PATCH/PUT /tic_tac_toe_boards/1 or /tic_tac_toe_boards/1.json
  def update
    @tic_tac_toe_board&.tic_tac_toe_players.where("tic_tac_toe_players.is_active is true")&.first
    @tic_tac_toe_board.update(params[:location] => params[:initial])
    check_the_winners = TicTacToeBoard.where(id: @tic_tac_toe_board.id).where("
      (a1 = :initial AND a2 = :initial AND a3 = :initial) OR
      (b1 = :initial AND b2 = :initial AND b3 = :initial) OR
      (c1 = :initial AND c2 = :initial AND c3 = :initial) OR
      (a1 = :initial AND b1 = :initial AND c1 = :initial) OR
      (a2 = :initial AND b2 = :initial AND c2 = :initial) OR
      (a3 = :initial AND b3 = :initial AND c3 = :initial) OR
      (a1 = :initial AND b2 = :initial AND c3 = :initial) OR
      (c1 = :initial AND b2 = :initial AND a3 = :initial)
    ", initial: params[:initial]).exists?
    
    @the_winners = "-"
    if check_the_winners
      @tic_tac_toe_board.update(game_state: 'finished')
      @tic_tac_toe_board&.tic_tac_toe_players&.where("tic_tac_toe_players.initial = ?", params[:initial])&.first&.update(is_winners: true)
      @the_winners = @tic_tac_toe_board&.tic_tac_toe_players&.where("tic_tac_toe_players.is_winners = ?", true)&.first&.user&.username
    end

    player_active = @tic_tac_toe_board&.tic_tac_toe_players.where("tic_tac_toe_players.is_active is true")&.first
    player_non_active = @tic_tac_toe_board&.tic_tac_toe_players.where("tic_tac_toe_players.is_active is false")&.first
    player_active&.update(is_active: false)
    player_non_active&.update(is_active: true)
    
    @player1 = @tic_tac_toe_board&.tic_tac_toe_players&.first&.user&.username
    @player2 = @tic_tac_toe_board&.tic_tac_toe_players&.last&.user&.username
    @turn_on_play = @tic_tac_toe_board&.tic_tac_toe_players.where("tic_tac_toe_players.is_active is true")&.first
    @initial = @turn_on_play&.initial
    @initial = @initial.present? ? @initial : 'X'
    @user_turn_on_play = @turn_on_play&.user&.username

    respond_to do |format|
      format.js { render :get_table }
    end
  end

  # DELETE /tic_tac_toe_boards/1 or /tic_tac_toe_boards/1.json
  def destroy
    @tic_tac_toe_board.destroy

    respond_to do |format|
      format.html { redirect_to tic_tac_toe_boards_url, notice: "Tic tac toe board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_table
    
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tic_tac_toe_board
      @tic_tac_toe_board = TicTacToeBoard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tic_tac_toe_board_params
      params.fetch(:tic_tac_toe_board, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tic_tac_toe_boards_helper.rb
module TicTacToeBoardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <%= yield(:javascript) %>
</html>

app/views/tic_tac_toe_boards/_detail.erb
<div class="col-md-6">
    <h1><u>Tic Tac Toe Board</u></h1>
    <br>
    <h4><%= @player1 %> VS <%= @player2 %></h4>
    <hr>
    <h4>Pemenang: <%= @the_winners %></h4>
    <hr>
    <h4>Giliran: <%= @user_turn_on_play %> (<%= @initial %>)</h4>
    <hr>
    <table class='table border' border=1>
        <% ('a'..'c').each do |row| %>
            <tr>
            <% ('1'..'3').each do |col| %>
                <td style="text-align: center">
                <% value = @tic_tac_toe_board.send("#{row}#{col}") %>
                <%= (value.present? || @tic_tac_toe_board.game_state.eql?('finished')) ? value : button_tag('', type: 'button', class: 'btn-board applyBoard', data: { id: @tic_tac_toe_board.id, location: "#{row}#{col}", initial: @initial}) %>
                </td>
            <% end %>
            </tr>
        <% end %>
        </table>
    <%= link_to 'Back', tic_tac_toe_boards_path %>
</div>

app/views/tic_tac_toe_boards/_form.html.erb
<%= form_with(model: tic_tac_toe_board, local: true) do |form| %>
  <% if tic_tac_toe_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tic_tac_toe_board.errors.count, "error") %> prohibited this tic_tac_toe_board from being saved:</h2>

      <ul>
      <% tic_tac_toe_board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

      <div>
    </div>
  <% end %>
  
  <div class="form-group">
    <div class="col-sm-6 col-md-4">
      <%= form.label :name, 'Nama Player 1', class: 'col-sm-12 requiredStar' %>
      <%= text_field_tag "users[][username]", nil, autofocus: true, required: true, class:  "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-6 col-md-4">
      <%= form.label :name, 'Nama Player 2', class: 'col-sm-12 requiredStar' %>
      <%= text_field_tag "users[][username]", nil, autofocus: true, required: true, class:  "form-control" %>
    </div>
    
  </div>

  <div class="form-group">
    <div class="col-sm-6 col-md-8">
      <%= form.submit 'Mulai Permainan', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tic_tac_toe_boards/edit.html.erb
<h1>Editing Tic Tac Toe Board</h1>

<%= render 'form', tic_tac_toe_board: @tic_tac_toe_board %>

<%= link_to 'Show', @tic_tac_toe_board %> |
<%= link_to 'Back', tic_tac_toe_boards_path %>

app/views/tic_tac_toe_boards/get_table.js.erb
$('#append_table').html("<%= j(render 'tic_tac_toe_boards/detail') %>");
console.log("----- masuk ----------")

app/views/tic_tac_toe_boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tic Tac Toe Boards</h1>

<div class="row">
  <div class="col-md-6">
    <%= link_to 'New Tic Tac Toe Board', new_tic_tac_toe_board_path, class: 'btn' %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Players</th>
          <th colspan="3">Action</th>
        </tr>
      </thead>

      <tbody>
        <% @tic_tac_toe_boards.each do |tic_tac_toe_board| %>
          <tr>
            <td><%= tic_tac_toe_board.tic_tac_toe_players.first.user.username %> VS <%= tic_tac_toe_board.tic_tac_toe_players.last.user.username %></td>
            <td><%= link_to 'Show', tic_tac_toe_board %></td>
            <!-- <td><%#= link_to 'Edit', edit_tic_tac_toe_board_path(tic_tac_toe_board) %></td>
            <td><%#= link_to 'Destroy', tic_tac_toe_board, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tic_tac_toe_boards/new.html.erb
<h1>New Tic Tac Toe Board</h1>

<%= render 'form', tic_tac_toe_board: @tic_tac_toe_board %>

<%#= link_to 'Back', tic_tac_toe_boards_path %>
<div class="form-group">
  <div class="col-sm-6 col-md-8">
    <%= link_to 'Back', tic_tac_toe_boards_path, class: 'btn' %>
  </div>
</div>

app/views/tic_tac_toe_boards/show.html.erb
<style>
.btn-board {
    width: 100%;
    height: 31px;
    margin-top: 0px;
    margin-bottom: 0px;
    color: #ffff;
    background: #fff;
    border: 0px;
    cursor: pointer;
}
</style>

<p id="notice"><%= notice %></p>

<div id="append_table">
    <%= render 'detail' %>
</div>

<%= content_for :javascript do %>
  <script>
    $(document).ready(function () {
        $("body").on("click", ".applyBoard", function () {
            var id = $(this).data('id');
            var location = $(this).data('location');
            var initial = $(this).data('initial');
            console.log("Clicked on id:", id);
            console.log("Clicked on location:", location);
            // Di sini Anda dapat menambahkan logika untuk menangani klik pada lokasi tertentu di papan permainan
            $.ajax({
                url: "/tic_tac_toe_boards/" + id + ".js",
                type: "PATCH",
                data: {
                    id: id,
                    location: location,
                    initial: initial,
                    authenticity_token: $('meta[name="csrf-token"]').attr('content')
                },
                success: function (response) {
                },
                error: function (request, status, error) {
                },
            });
        });
    });
  </script>
<% end %>